name: Tests

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: app_test
        ports:
          - 5432:5432

    env:
      NODE_ENV: test
      PORT: 3000

      DATABASE_URL: postgresql://postgres:admin@localhost:5432/app_test

      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET}}
      TOKEN_EXPIRATION: ${{ secrets.TOKEN_EXPIRATION}}

      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET}}
      REFRESH_TOKEN_EXPIRATION: ${{ secrets.REFRESH_TOKEN_EXPIRATION}}

      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL}}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run tests
        run: npm test
